## Arrays In Python

## Arrays 

### pip3 install package_name_here

### pip3 install numpy 

### import package as alias

> In list each element is has its own type 

> In numpy array it convert all the elemnts into most compatible type 


In [2]:
import numpy as np
list =  [1,2,3,4,5]
np_list = np.array(list)
print("List is  = ", list)
print("Numpy array is", np_list)

List is  =  [1, 2, 3, 4, 5]
Numpy array is [1 2 3 4 5]


## Create an array
You can use the NumPy package to create arrays. NumPy arrays are optimized for numerical analyses and contain only a single data type. To convert a list to an array, you can use the array() function from NumPy.

import numpy as np

a_list = [1, 2, 3, 4]
a_list

[1, 2, 3, 4]

an_array = np.array(a_list)
an_array

array([1, 2, 3, 4])

## Instructions

> Import numpy using the alias np.

>Create prices_array and earnings_array arrays from the lists prices and earnings, respectively.

In [23]:
# Import numpy as np
import numpy as np 

# Lists
prices = [170.12, 93.29, 55.28, 145.30, 171.81, 59.50, 100.50]
earnings = [9.2, 5.31, 2.41, 5.91, 15.42, 2.51, 6.79]

# NumPy arrays
prices_array = np.array(prices)
earnings_array = np.array(earnings)

# Print the arrays
print(prices_array)
print(earnings_array)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]


## Elementwise operations on arrays
Arrays allow for efficient numerical manipulation of its elements. Let's explore element-wise mathematical operations by calculating price to earnings ratio using two arrays, prices_array and earnings_array from the previous exercise.

This price to earnings ratio, or PE ratio, is a financial indicator of the dollar amount an investor can expect to invest in a company in order to receive one dollar of that company’s earnings.

prices_array and earnings_array are available in your workspace.

## Instructions

> Import numpy as np.

> Create pe_array by dividing prices_array by earnings_array.

In [24]:
# Import numpy as np
import numpy as np

# Create PE ratio array
pe_array = prices_array/earnings_array

# Print pe_array
print(pe_array)

[18.49130435 17.56873823 22.93775934 24.58544839 11.14202335 23.70517928
 14.8011782 ]


## Subsetting elements from an array
Subsetting arrays is similar to subsetting lists. In this exercise, you will practice just that.

numpy is imported as np and prices_array is available in your workspace.

## Instructions 1/3

> Subset the first three elements from prices_array.

> Subset the last three elements from the prices_array using negative index slicing.

> Subset every third element from the prices_array using step slicing.

In [25]:
# Subset the first three elements
prices_subset_1 = prices_array[0:3]
print(prices_subset_1)
print()
# Subset last three elements 
prices_subset_2 = prices_array[-3:]
print(prices_subset_2)
print()
# Subset every third element
prices_subset_3 = prices_array[0:7:3]
print(prices_subset_3)

[170.12  93.29  55.28]

[171.81  59.5  100.5 ]

[170.12 145.3  100.5 ]


## 2-Dimensional Array

## data.shape()

## data.size()


In [18]:
import numpy as np 
months =  [1,2,3,4]
prices = [10,20,30,5]
cpi_array = np.array([months,prices])
print(cpi_array)
print()
print(cpi_array.shape)
print()
print(cpi_array.size)
print()
print(cpi_array.mean())
print()
sample_months = np.arange(1,15)
print(sample_months)
print()
odd_nos =  np.arange(1,20,2)
print(odd_nos)
print()
even_nos =  np.arange(2,20,2)
print(even_nos)
print()
print("Transpose of array",np.transpose(cpi_array))

[[ 1  2  3  4]
 [10 20 30  5]]

(2, 4)

8

9.375

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 1  3  5  7  9 11 13 15 17 19]

[ 2  4  6  8 10 12 14 16 18]

Transpose of array [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4  5]]


## Creating a 2D array
Multi-dimensional arrays can be useful for several tasks. In finance, for example, a 2D array may be used to store the prices and earnings for various companies. Let's create this 2D array, stock_array, from a list of prices and earnings.

numpy is imported as np and the two lists prices and earnings are available in your workspace.

## Instructions 1/2

> Create a two dimensional array of prices and earnings (in that order) and assign it to stock_array.

> Print the shape of stock_array.

> Transpose stock_array and assign the result to stock_array_transposed.

> Print the size of stock_array_transposed.

>Extract the first column from stock_array_transposed and assign it to prices.


In [27]:
# Create a 2D array of prices and earnings
stock_array = np.array([prices,earnings])
print(stock_array)
print()
# Print the shape of stock_array
print(stock_array.shape)
print()
# Print the size of stock_array
print(stock_array.size)
print()

# Transpose stock_array
stock_array_transposed = np.transpose(stock_array)
print(stock_array_transposed)
print()
# Print the shape of stock_array
print(stock_array_transposed.shape)
print()
# Print the size of stock_array
print(stock_array_transposed.size)
print()

[[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]
 [  9.2    5.31   2.41   5.91  15.42   2.51   6.79]]

(2, 7)

14

[[170.12   9.2 ]
 [ 93.29   5.31]
 [ 55.28   2.41]
 [145.3    5.91]
 [171.81  15.42]
 [ 59.5    2.51]
 [100.5    6.79]]

(7, 2)

14



## Subsetting 2D arrays
Subsetting 2D arrays is similar to subsetting nested lists. In a 2D array, the indexing or slicing must be specific to the dimension of the array:

array[row_index, column_index]
numpy is imported as np and the 2D array stock_array_transposed (from the previous exercise) is available in your workspace.

## Instructions 1/3

> Extract the first column from stock_array_transposed and assign it to prices.

In [28]:
# Subset prices from stock_array_transposed
prices = stock_array_transposed[:, 0]
print(prices)
print()
# Subset earnings from stock_array_transposed
earnings = stock_array_transposed[:,1]
print(earnings)
print()
# Subset the price and earning for first company
company_1 = stock_array_transposed[0]
print(company_1)

[170.12  93.29  55.28 145.3  171.81  59.5  100.5 ]

[ 9.2   5.31  2.41  5.91 15.42  2.51  6.79]

[170.12   9.2 ]


### Calculating array stats
Not only can you perform elementwise calculations on NumPy arrays, you can also calculate summary stats such as mean and standard deviation of arrays using functions from NumPy.

numpy is imported as np and the array prices (from the previous exercise) is available in your workspace.

## Instructions 1/2

> Calculate the mean of prices.

> Calculate the standard deviation of prices.

In [31]:
# Calculate the mean 
prices_mean = np.mean(prices)
print("Mean is ", prices_mean)

# Calculate the standard deviation 
prices_std = np.std(prices)
print("STD is ",prices_std)
      

Mean is  113.6857142857143
STD is  45.51277932221513


## Generating a sequence of numbers
You may want to create an array of a range of numbers (e.g., 1 to 10) without having to type in every single number. The NumPy function arange() is an efficient way to create numeric arrays of a range of numbers. The arguments for arange() include the start, stop, and step interval as shown below:

np.arange(start, stop, step)
numpy is imported as np.

## Instructions

> Create an array company_ids containing the numbers 1 through 7 (inclusive).

> Create an array company_ids_odd containing only the odd numbers from 1 through 7 (inclusive).

In [32]:
# Create and print company_ids
company_ids = np.arange(1, 8, 1)
print(company_ids)

# Create and print company_ids_odd
company_ids_odd = np.arange(1, 8, 2)
print(company_ids_odd)

[1 2 3 4 5 6 7]
[1 3 5 7]


## Using arrays for analysis

In [22]:
months = ['Jan',"Feb",'Mar','April','May','Jun']
months_arr  = np.array(months)
print(months_arr)
index_arr = np.array([1,3,5])

months_subset =  months_arr[index_arr]
print(months_subset)


['Jan' 'Feb' 'Mar' 'April' 'May' 'Jun']
['Feb' 'April' 'Jun']


## Who's above average?
Boolean arrays can be a very powerful way to subset arrays. In this exercise, you will identify the prices that are greater than average from a list of prices.

numpy is imported as np and the array prices is available in your workspace.

## Instructions

> Find elements in prices that are greater than price_mean and assign the boolean result to boolean_array.

> Subset prices using boolean_array and assign the result to above_avg.

In [33]:
# Find the mean
price_mean = np.mean(prices)

# Create boolean array
boolean_array = (prices>price_mean)
print(boolean_array)

# Select prices that are greater than average
above_avg = prices[boolean_array]
print(above_avg)

[ True False False  True  True False False]
[170.12 145.3  171.81]


## Who's in health care?
In this exercise, you are provided the names of companies with their associated sector, and your goal is to find all companies that are associated with health care sector.

numpy is imported as np and the arrays names and sectors are available in your workspace.

## Instructions

> Find elements in sectors that are equivalent to 'Health Care' and assign the result to boolean_array.

> Subset names using boolean_array and assign the result to health_care.

In [36]:
# Create boolean array
names =  ['Apple Inc', 'Abbvie Inc', 'Abbott Laboratories',
       'Accenture Technologies', 'Allergan Plc']
sectors=  ['Information Technology', 'Health Care', 'Health Care',
             'Information Technologies', 'Health Care']
boolean_array = (sectors == 'Health Care')
print(boolean_array)

# Print only health care companies
health_care = names[boolean_array]
print(health_care)

False
Apple Inc
